export interface SwarmAudiobook {
  id: string;
  rawTitle: string;
  title: string;
  author: string;
  url: string;
  cover: string;
  categories: string[];
  format: string;
  bitrate: string;
  size: string;
  infoHash: string;
  source: string;
  description?: string;
  duration?: string;
  narrator?: string;
}

export const MASTER_AUDIOBOOKS: SwarmAudiobook[] = [
  // Sci-Fi
  {
    id: "projhailmary",
    rawTitle: "Project Hail Mary - Andy Weir",
    title: "Project Hail Mary",
    author: "Andy Weir",
    narrator: "Ray Porter",
    duration: "16 hrs and 10 mins",
    description: "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself are doomed.",
    url: "https://audiobookbay.lu/abss/project-hail-mary-andy-weir/",
    cover: "https://is1-ssl.mzstatic.com/image/thumb/Publication115/v4/71/84/02/718402f0-7b56-3a7a-6242-7ef6a72e817a/9781473582880.jpg/1200x1200bb.jpg",
    categories: ["Sci-Fi", "Bestsellers"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "890 MB",
    infoHash: "0f54898dc1b8e49d96e32827377f651ea6c935af",
    source: "torrent"
  },
  {
    id: "dune1",
    rawTitle: "Dune - Frank Herbert",
    title: "Dune",
    author: "Frank Herbert",
    narrator: "Scott Brick, Orlagh Cassidy",
    duration: "21 hrs and 2 mins",
    description: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world.",
    url: "https://audiobookbay.lu/abss/dune-frank-herbert/",
    cover: "https://is1-ssl.mzstatic.com/image/thumb/Publication124/v4/d5/4b/f2/d54bf2ec-9a10-23a5-2965-0a3731110f0f/9781473501799.jpg/1200x1200bb.jpg",
    categories: ["Sci-Fi", "Classic", "Bestsellers"],
    format: "M4B",
    bitrate: "96 Kbps",
    size: "9.7 GB",
    infoHash: "f4425771c01f25a7bb940e8e3027e0881c4a5212",
    source: "torrent"
  },
  {
    id: "martian1",
    rawTitle: "The Martian - Andy Weir",
    title: "The Martian",
    author: "Andy Weir",
    narrator: "R.C. Bray",
    duration: "10 hrs and 53 mins",
    description: "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there.",
    url: "https://audiobookbay.lu/abss/the-martian-andy-weir/",
    cover: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?q=80&w=600",
    categories: ["Sci-Fi", "Adventure", "Bestsellers"],
    format: "MP3",
    bitrate: "64 Kbps",
    size: "313 MB",
    infoHash: "079a2887bb3ac78680d1c3766773f6cbf4169d05",
    source: "torrent"
  },
  {
    id: "neuromancer1",
    rawTitle: "Neuromancer - William Gibson",
    title: "Neuromancer",
    author: "William Gibson",
    narrator: "Robertson Dean",
    duration: "10 hrs and 31 mins",
    description: "The definitive cyberpunk novel that coined the term 'matrix' and predicted cyberspace, corporate warfare, and AI consciousness.",
    url: "https://audiobookbay.lu/abss/neuromancer-william-gibson/",
    cover: "https://covers.openlibrary.org/b/id/8235116-L.jpg",
    categories: ["Sci-Fi", "Classic"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "863 MB",
    infoHash: "191bd1f7597d7c3f1c9925c464b3c6443d4810f0",
    source: "torrent"
  },
  {
    id: "threebody1",
    rawTitle: "The Three-Body Problem - Cixin Liu",
    title: "The Three-Body Problem",
    author: "Cixin Liu",
    narrator: "Luke Daniels",
    duration: "13 hrs and 26 mins",
    description: "Set against the backdrop of China's Cultural Revolution, a secret military project sends signals into space to establish contact with aliens.",
    url: "https://audiobookbay.lu/abss/the-three-body-problem-cixin-liu/",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600",
    categories: ["Sci-Fi", "Mystery"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "396 MB",
    infoHash: "3affccb854830df88b9f7880837cc0ef509a7828",
    source: "torrent"
  },

  // Fantasy & Full Cast
  {
    id: "hpfullcast",
    rawTitle: "Harry Potter Full-Cast Audio Editions",
    title: "Harry Potter: Full-Cast Audio Editions",
    author: "J.K. Rowling",
    narrator: "Full Cast Production",
    duration: "Complete 7-Book Collection",
    description: "The legendary Harry Potter saga brought to life in an immersive full-cast audio dramatization with original sound effects and musical score.",
    url: "https://audiobookbay.lu/abss/harry-potter-full-cast-audio-editions/",
    cover: "https://is1-ssl.mzstatic.com/image/thumb/Publication221/v4/6c/58/6b/6c586b29-afa0-4595-80ea-12bf914e33e2/9781781105900.jpg/1200x1200bb.jpg",
    categories: ["Fantasy", "Young Adult", "Bestsellers"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "6.5 GB",
    infoHash: "757c478f66a1a619f2a935dbcdb83fb162b8e4f9",
    source: "torrent"
  },
  {
    id: "hphallows",
    rawTitle: "Harry Potter Complete Series 1-7 - Stephen Fry",
    title: "Harry Potter: Complete Series (Stephen Fry)",
    author: "J.K. Rowling",
    narrator: "Stephen Fry",
    duration: "124 hrs total",
    description: "The complete, critically-acclaimed Harry Potter series narrated by British icon Stephen Fry, featuring all 7 books unabridged.",
    url: "https://audiobookbay.lu/abss/harry-potter-audio-books-1-7-read-by-stephen-fry-mp3/",
    cover: "https://is1-ssl.mzstatic.com/image/thumb/Publication221/v4/6c/58/6b/6c586b29-afa0-4595-80ea-12bf914e33e2/9781781105900.jpg/1200x1200bb.jpg",
    categories: ["Fantasy", "Young Adult", "Classic"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "1.35 GB",
    infoHash: "66132602c1981e3e77489086f8af35b903d0643c",
    source: "torrent"
  },
  {
    id: "hobbit1",
    rawTitle: "The Hobbit - J.R.R. Tolkien",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    narrator: "Rob Inglis",
    duration: "10 hrs and 25 mins",
    description: "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life. But his contentment is disturbed when Gandalf arrives with thirteen dwarves.",
    url: "https://audiobookbay.lu/abss/the-hobbit-j-r-r-tolkien/",
    cover: "https://is1-ssl.mzstatic.com/image/thumb/Publication115/v4/05/1f/ff/051fff0d-5bc3-a9d9-480a-9d9059f13e73/9780007525508.jpg/1200x1200bb.jpg",
    categories: ["Fantasy", "Adventure", "Classic"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "3.7 GB",
    infoHash: "2dad2c14cce6c02d86d07c929446d75186aca96d",
    source: "torrent"
  },
  {
    id: "lotr1",
    rawTitle: "The Fellowship of the Ring - J.R.R. Tolkien",
    title: "The Fellowship of the Ring",
    author: "J.R.R. Tolkien",
    narrator: "Rob Inglis",
    duration: "22 hrs and 38 mins",
    description: "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them.",
    url: "https://audiobookbay.lu/abss/the-fellowship-of-the-ring-j-r-r-tolkien/",
    cover: "https://covers.openlibrary.org/b/id/8314134-L.jpg",
    categories: ["Fantasy", "Adventure", "Classic", "Bestsellers"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "579 MB",
    infoHash: "458459567d82d08f32407044a4abd00aee9d0d84",
    source: "torrent"
  },
  {
    id: "wayofkings1",
    rawTitle: "The Way of Kings - Brandon Sanderson",
    title: "The Way of Kings",
    author: "Brandon Sanderson",
    narrator: "Michael Kramer, Kate Reading",
    duration: "45 hrs and 37 mins",
    description: "Roshar is a world of stone and storms. Uncanny tempests of incredible power sweep out across the rocky terrain.",
    url: "https://audiobookbay.lu/abss/the-way-of-kings-brandon-sanderson/",
    cover: "https://covers.openlibrary.org/b/id/8231996-L.jpg",
    categories: ["Fantasy", "Adventure"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "444 MB",
    infoHash: "16d2d7fc4b5680c92dc3d812c8c57b7ccc56ff5b",
    source: "torrent"
  },
  {
    id: "namewind1",
    rawTitle: "The Name of the Wind - Patrick Rothfuss",
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    narrator: "Nick Podehl",
    duration: "27 hrs and 55 mins",
    description: "The riveting first-person narrative of Kvothe, from his childhood in a troupe of traveling players to his years as a mythic wizard and kingkiller.",
    url: "https://audiobookbay.lu/abss/the-name-of-the-wind-patrick-rothfuss/",
    cover: "https://covers.openlibrary.org/b/id/8226191-L.jpg",
    categories: ["Fantasy", "Adventure"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "743 MB",
    infoHash: "95e9e49a0970a91e91326967a94686dea6439c0a",
    source: "torrent"
  },
  {
    id: "sandman1",
    rawTitle: "The Sandman - Neil Gaiman, Dirk Maggs",
    title: "The Sandman (Full Cast)",
    author: "Neil Gaiman",
    narrator: "James McAvoy, Neil Gaiman, Full Cast",
    duration: "10 hrs and 54 mins",
    description: "Audible Original full-cast audio adaptation of Neil Gaiman's iconic DC comic series, directed by Dirk Maggs with music by Harry Escott.",
    url: "https://audiobookbay.lu/abss/the-sandman-neil-gaiman-dirk-maggs-2020/",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600",
    categories: ["Fantasy", "Graphic Audio", "Bestsellers"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "623 MB",
    infoHash: "d37d1d1fa69afc98a1944c77f0d584d6227897d8",
    source: "torrent"
  },

  // Thriller & Mystery
  {
    id: "shining1",
    rawTitle: "The Shining - Stephen King",
    title: "The Shining",
    author: "Stephen King",
    narrator: "Campbell Scott",
    duration: "15 hrs and 49 mins",
    description: "Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. But as winter sets in, the sinister forces gather.",
    url: "https://audiobookbay.lu/abss/the-shining-stephen-king-audiobook/",
    cover: "https://covers.openlibrary.org/b/id/8235114-L.jpg",
    categories: ["Mystery", "Thriller", "Horror"],
    format: "MP3",
    bitrate: "64 Kbps",
    size: "458 MB",
    infoHash: "ccada01513d7e970931ac6198044cb337d314d67",
    source: "torrent"
  },
  {
    id: "gonegirl1",
    rawTitle: "Gone Girl - Gillian Flynn",
    title: "Gone Girl",
    author: "Gillian Flynn",
    narrator: "Julia Whelan, Kirby Heyborne",
    duration: "19 hrs and 11 mins",
    description: "On a warm summer morning in North Carthage, Missouri, it is Nick and Amy Dunne’s fifth wedding anniversary. That is the morning Amy disappears.",
    url: "https://audiobookbay.lu/abss/gone-girl-gillian-flynn/",
    cover: "https://covers.openlibrary.org/b/id/8404285-L.jpg",
    categories: ["Mystery", "Thriller"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "553 MB",
    infoHash: "994e26910c8d1fec437c55f774b2df906b8e4dc2",
    source: "torrent"
  },
  {
    id: "davinci1",
    rawTitle: "The Da Vinci Code - Dan Brown",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    narrator: "Paul Michael",
    duration: "17 hrs and 58 mins",
    description: "While in Paris, Harvard symbologist Robert Langdon receives an urgent call: the elderly curator of the Louvre has been murdered inside the museum.",
    url: "https://audiobookbay.lu/abss/the-da-vinci-code-dan-brown/",
    cover: "https://covers.openlibrary.org/b/id/8225261-L.jpg",
    categories: ["Mystery", "Thriller", "Bestsellers"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "458 MB",
    infoHash: "c9abbb804809b64059b847d2bc1b0bf10be4a542",
    source: "torrent"
  },
  {
    id: "sherlock1",
    rawTitle: "Sherlock Holmes: The Definitive Audio Collection - Arthur Conan Doyle",
    title: "Sherlock Holmes: Complete Audio Collection",
    author: "Arthur Conan Doyle",
    narrator: "Stephen Fry",
    duration: "62 hrs and 52 mins",
    description: "Stephen Fry’s definitive recording of Arthur Conan Doyle’s complete Sherlock Holmes works, with personal introductions for each collection.",
    url: "https://audiobookbay.lu/abss/sherlock-holmes-definitive-arthur-conan-doyle/",
    cover: "https://covers.openlibrary.org/b/id/8235122-L.jpg",
    categories: ["Mystery", "Classic"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "2.06 GB",
    infoHash: "b172aa22498abc9571e1f37b5ce3c4b8c0dd09d2",
    source: "torrent"
  },

  // Self Help & Business
  {
    id: "atomichabits",
    rawTitle: "Atomic Habits - James Clear",
    title: "Atomic Habits",
    author: "James Clear",
    narrator: "James Clear",
    duration: "5 hrs and 35 mins",
    description: "Tiny Changes, Remarkable Results: An easy and proven way to build good habits and break bad ones.",
    url: "https://audiobookbay.lu/abss/atomic-habits-james-clear/",
    cover: "https://is1-ssl.mzstatic.com/image/thumb/Publication124/v4/9f/fa/b1/9ffab177-c377-2e1d-84ad-e80629ec2e9e/9781473565425.jpg/1200x1200bb.jpg",
    categories: ["Business", "Self Help", "Bestsellers"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "159 MB",
    infoHash: "51eb9f733ceb792822d6cfa62b0a033b7b3732b1",
    source: "torrent"
  },
  {
    id: "sapiens1",
    rawTitle: "Sapiens: A Brief History of Humankind - Yuval Noah Harari",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    narrator: "Derek Perkins",
    duration: "15 hrs and 17 mins",
    description: "One hundred thousand years ago, at least six different species of humans inhabited Earth. Yet today there is only one: Homo sapiens.",
    url: "https://audiobookbay.lu/abss/sapiens-yuval-noah-harari/",
    cover: "https://covers.openlibrary.org/b/id/8315112-L.jpg",
    categories: ["Business", "Self Help", "Bestsellers"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "220 MB",
    infoHash: "040212fe7dbb29f3b9672b91318783f15559e8f2",
    source: "torrent"
  },
  {
    id: "deepwork1",
    rawTitle: "Deep Work - Cal Newport",
    title: "Deep Work: Rules for Focused Success",
    author: "Cal Newport",
    narrator: "Jeff Bottoms",
    duration: "7 hrs and 44 mins",
    description: "Deep work is the ability to focus without distraction on a cognitively demanding task, supercharging your productivity.",
    url: "https://audiobookbay.lu/abss/deep-work-cal-newport/",
    cover: "https://covers.openlibrary.org/b/id/8235128-L.jpg",
    categories: ["Business", "Self Help"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "223 MB",
    infoHash: "97293b9fa1992fa8223aafef4df154b90bfb4c2c",
    source: "torrent"
  },
  {
    id: "thinkingfast1",
    rawTitle: "Thinking, Fast and Slow - Daniel Kahneman",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    narrator: "Patrick Egan",
    duration: "20 hrs and 2 mins",
    description: "The groundbreaking tour of the mind explaining the two systems that drive the way we think: fast intuitive thinking, and slow deliberate thinking.",
    url: "https://audiobookbay.lu/abss/thinking-fast-and-slow-daniel-kahneman/",
    cover: "https://covers.openlibrary.org/b/id/8235130-L.jpg",
    categories: ["Business", "Self Help"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "721 MB",
    infoHash: "c1cac79c8e7a95090cc4a699e3213aa379764e65",
    source: "torrent"
  },

  // Classics
  {
    id: "1984george",
    rawTitle: "1984 - George Orwell",
    title: "1984",
    author: "George Orwell",
    narrator: "Simon Prebble",
    duration: "11 hrs and 22 mins",
    description: "Winston Smith lives in a world of perpetual war, omnipresent government surveillance, and historical negationism governed by Big Brother.",
    url: "https://audiobookbay.lu/abss/1984-george-orwell/",
    cover: "https://covers.openlibrary.org/b/id/8225631-L.jpg",
    categories: ["Classic", "Sci-Fi", "Bestsellers"],
    format: "MP3",
    bitrate: "64 Kbps",
    size: "288 MB",
    infoHash: "c4de2bef418468a1343fb73d604a83ba2ffb28d7",
    source: "torrent"
  },
  {
    id: "dracula1",
    rawTitle: "Dracula - Bram Stoker",
    title: "Dracula",
    author: "Bram Stoker",
    narrator: "BBC Dramatised Cast",
    duration: "16 hrs and 31 mins",
    description: "The gothic masterpiece that created the legend of Count Dracula and his journey from Transylvania to Victorian England.",
    url: "https://audiobookbay.lu/abss/dracula-bram-stoker/",
    cover: "https://covers.openlibrary.org/b/id/8235135-L.jpg",
    categories: ["Classic", "Mystery", "Horror"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "197 MB",
    infoHash: "c0e0ba7a54619ecb87735af21bb8bef53a8ab350",
    source: "torrent"
  },
  {
    id: "pride1",
    rawTitle: "Pride and Prejudice - Jane Austen",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    narrator: "Kate Reading",
    duration: "11 hrs and 35 mins",
    description: "The romantic clash between the opinionated Elizabeth Bennet and the enigmatic Mr. Darcy in early 19th-century England.",
    url: "https://audiobookbay.lu/abss/pride-and-prejudice-jane-austen/",
    cover: "https://covers.openlibrary.org/b/id/8235132-L.jpg",
    categories: ["Classic", "Romance"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "379 MB",
    infoHash: "4b7f8fb530f327c6f5a1c3083649ab68143f9fb9",
    source: "torrent"
  }
];
