export interface SwarmAudiobook {
  id: string;
  rawTitle: string;
  title: string;
  author: string;
  url: string;
  cover: string;
  categories: string[];
  format: string;
  bitrate: string;
  size: string;
  infoHash: string;
  source: string;
  description?: string;
  duration?: string;
  narrator?: string;
}

export const MASTER_AUDIOBOOKS: SwarmAudiobook[] = [
  // Sci-Fi
  {
    id: "projhailmary",
    rawTitle: "Project Hail Mary - Andy Weir",
    title: "Project Hail Mary",
    author: "Andy Weir",
    narrator: "Ray Porter",
    duration: "16 hrs and 10 mins",
    description: "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself are doomed.",
    url: "https://audiobookbay.lu/abss/project-hail-mary-andy-weir/",
    cover: "https://is1-ssl.mzstatic.com/image/thumb/Publication115/v4/71/84/02/718402f0-7b56-3a7a-6242-7ef6a72e817a/9781473582880.jpg/1200x1200bb.jpg",
    categories: ["Sci-Fi", "Bestsellers"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "480 MB",
    infoHash: "2b0931d87e02e0b51a0293ec485d9fa5bb6f7cb1",
    source: "torrent"
  },
  {
    id: "dune1",
    rawTitle: "Dune - Frank Herbert",
    title: "Dune",
    author: "Frank Herbert",
    narrator: "Scott Brick, Orlagh Cassidy",
    duration: "21 hrs and 2 mins",
    description: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world.",
    url: "https://audiobookbay.lu/abss/dune-frank-herbert/",
    cover: "https://is1-ssl.mzstatic.com/image/thumb/Publication124/v4/d5/4b/f2/d54bf2ec-9a10-23a5-2965-0a3731110f0f/9781473501799.jpg/1200x1200bb.jpg",
    categories: ["Sci-Fi", "Classic", "Bestsellers"],
    format: "M4B",
    bitrate: "96 Kbps",
    size: "820 MB",
    infoHash: "5b54637da8c139db4cb89d9804c86e0c6a28ce40",
    source: "torrent"
  },
  {
    id: "martian1",
    rawTitle: "The Martian - Andy Weir",
    title: "The Martian",
    author: "Andy Weir",
    narrator: "R.C. Bray",
    duration: "10 hrs and 53 mins",
    description: "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there.",
    url: "https://audiobookbay.lu/abss/the-martian-andy-weir/",
    cover: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?q=80&w=600",
    categories: ["Sci-Fi", "Adventure", "Bestsellers"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "410 MB",
    infoHash: "6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b",
    source: "torrent"
  },
  {
    id: "neuromancer1",
    rawTitle: "Neuromancer - William Gibson",
    title: "Neuromancer",
    author: "William Gibson",
    narrator: "Robertson Dean",
    duration: "10 hrs and 31 mins",
    description: "The definitive cyberpunk novel that coined the term 'matrix' and predicted cyberspace, corporate warfare, and AI consciousness.",
    url: "https://audiobookbay.lu/abss/neuromancer-william-gibson/",
    cover: "https://covers.openlibrary.org/b/id/8235116-L.jpg",
    categories: ["Sci-Fi", "Classic"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "340 MB",
    infoHash: "8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d",
    source: "torrent"
  },
  {
    id: "threebody1",
    rawTitle: "The Three-Body Problem - Cixin Liu",
    title: "The Three-Body Problem",
    author: "Cixin Liu",
    narrator: "Luke Daniels",
    duration: "13 hrs and 26 mins",
    description: "Set against the backdrop of China's Cultural Revolution, a secret military project sends signals into space to establish contact with aliens.",
    url: "https://audiobookbay.lu/abss/the-three-body-problem-cixin-liu/",
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600",
    categories: ["Sci-Fi", "Mystery"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "520 MB",
    infoHash: "1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f",
    source: "torrent"
  },

  // Fantasy
  {
    id: "hphallows",
    rawTitle: "Harry Potter and the Deathly Hallows - J.K. Rowling",
    title: "Harry Potter and the Deathly Hallows",
    author: "J.K. Rowling",
    narrator: "Stephen Fry",
    duration: "24 hrs and 12 mins",
    description: "Harry Potter is leaving Privet Drive for the last time. But as the Dark Lord consolidates his grip, the final battle draws near.",
    url: "https://audiobookbay.lu/abss/harry-potter-and-the-deathly-hallows-j-k-rowling/",
    cover: "https://is1-ssl.mzstatic.com/image/thumb/Publication221/v4/6c/58/6b/6c586b29-afa0-4595-80ea-12bf914e33e2/9781781105900.jpg/1200x1200bb.jpg",
    categories: ["Fantasy", "Young Adult", "Bestsellers"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "650 MB",
    infoHash: "05877f88450125c15cf01614742a781b0a5a3a79",
    source: "torrent"
  },
  {
    id: "hobbit1",
    rawTitle: "The Hobbit - J.R.R. Tolkien",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    narrator: "Andy Serkis",
    duration: "10 hrs and 25 mins",
    description: "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life. But his contentment is disturbed when Gandalf arrives with thirteen dwarves.",
    url: "https://audiobookbay.lu/abss/the-hobbit-j-r-r-tolkien/",
    cover: "https://is1-ssl.mzstatic.com/image/thumb/Publication115/v4/05/1f/ff/051fff0d-5bc3-a9d9-480a-9d9059f13e73/9780007525508.jpg/1200x1200bb.jpg",
    categories: ["Fantasy", "Adventure", "Classic"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "540 MB",
    infoHash: "f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0",
    source: "torrent"
  },
  {
    id: "lotr1",
    rawTitle: "The Fellowship of the Ring - J.R.R. Tolkien",
    title: "The Fellowship of the Ring",
    author: "J.R.R. Tolkien",
    narrator: "Andy Serkis",
    duration: "22 hrs and 38 mins",
    description: "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them.",
    url: "https://audiobookbay.lu/abss/the-fellowship-of-the-ring-j-r-r-tolkien/",
    cover: "https://covers.openlibrary.org/b/id/8314134-L.jpg",
    categories: ["Fantasy", "Adventure", "Classic", "Bestsellers"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "910 MB",
    infoHash: "e5b29c951152a513ec8ff60e224e75685215ff5e",
    source: "torrent"
  },
  {
    id: "wayofkings1",
    rawTitle: "The Way of Kings - Brandon Sanderson",
    title: "The Way of Kings",
    author: "Brandon Sanderson",
    narrator: "Michael Kramer, Kate Reading",
    duration: "45 hrs and 37 mins",
    description: "Roshar is a world of stone and storms. Uncanny tempests of incredible power sweep out across the rocky terrain.",
    url: "https://audiobookbay.lu/abss/the-way-of-kings-brandon-sanderson/",
    cover: "https://covers.openlibrary.org/b/id/8231996-L.jpg",
    categories: ["Fantasy", "Adventure"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "1.4 GB",
    infoHash: "7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b",
    source: "torrent"
  },
  {
    id: "namewind1",
    rawTitle: "The Name of the Wind - Patrick Rothfuss",
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    narrator: "Nick Podehl",
    duration: "27 hrs and 55 mins",
    description: "The riveting first-person narrative of Kvothe, from his childhood in a troupe of traveling players to his years as a mythic wizard and kingkiller.",
    url: "https://audiobookbay.lu/abss/the-name-of-the-wind-patrick-rothfuss/",
    cover: "https://covers.openlibrary.org/b/id/8226191-L.jpg",
    categories: ["Fantasy", "Adventure"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "890 MB",
    infoHash: "3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e",
    source: "torrent"
  },

  // Thriller & Mystery
  {
    id: "silentpatient1",
    rawTitle: "The Silent Patient - Alex Michaelides",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    narrator: "Jack Hawkins, Louise Brealey",
    duration: "8 hrs and 43 mins",
    description: "Alicia Berenson’s life is seemingly perfect. Then, one evening, she shoots her husband five times in the face and never speaks another word.",
    url: "https://audiobookbay.lu/abss/the-silent-patient-alex-michaelides/",
    cover: "https://covers.openlibrary.org/b/id/8690374-L.jpg",
    categories: ["Mystery", "Thriller", "Bestsellers"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "380 MB",
    infoHash: "a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1",
    source: "torrent"
  },
  {
    id: "gonegirl1",
    rawTitle: "Gone Girl - Gillian Flynn",
    title: "Gone Girl",
    author: "Gillian Flynn",
    narrator: "Julia Whelan, Kirby Heyborne",
    duration: "19 hrs and 11 mins",
    description: "On a warm summer morning in North Carthage, Missouri, it is Nick and Amy Dunne’s fifth wedding anniversary. That is the morning Amy disappears.",
    url: "https://audiobookbay.lu/abss/gone-girl-gillian-flynn/",
    cover: "https://covers.openlibrary.org/b/id/8404285-L.jpg",
    categories: ["Mystery", "Thriller"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "520 MB",
    infoHash: "b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2",
    source: "torrent"
  },
  {
    id: "davinci1",
    rawTitle: "The Da Vinci Code - Dan Brown",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    narrator: "Paul Michael",
    duration: "17 hrs and 58 mins",
    description: "While in Paris, Harvard symbologist Robert Langdon receives an urgent call: the elderly curator of the Louvre has been murdered inside the museum.",
    url: "https://audiobookbay.lu/abss/the-da-vinci-code-dan-brown/",
    cover: "https://covers.openlibrary.org/b/id/8225261-L.jpg",
    categories: ["Mystery", "Thriller", "Bestsellers"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "460 MB",
    infoHash: "c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3",
    source: "torrent"
  },
  {
    id: "sherlock1",
    rawTitle: "Sherlock Holmes: The Definitive Audio Collection - Arthur Conan Doyle",
    title: "Sherlock Holmes: Complete Audio Collection",
    author: "Arthur Conan Doyle",
    narrator: "Stephen Fry",
    duration: "62 hrs and 52 mins",
    description: "Stephen Fry’s definitive recording of Arthur Conan Doyle’s complete Sherlock Holmes works, with personal introductions for each collection.",
    url: "https://audiobookbay.lu/abss/sherlock-holmes-definitive-arthur-conan-doyle/",
    cover: "https://covers.openlibrary.org/b/id/8235122-L.jpg",
    categories: ["Mystery", "Classic"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "1.8 GB",
    infoHash: "d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4",
    source: "torrent"
  },

  // Self Help & Business
  {
    id: "atomichabits",
    rawTitle: "Atomic Habits - James Clear",
    title: "Atomic Habits",
    author: "James Clear",
    narrator: "James Clear",
    duration: "5 hrs and 35 mins",
    description: "Tiny Changes, Remarkable Results: An easy and proven way to build good habits and break bad ones.",
    url: "https://audiobookbay.lu/abss/atomic-habits-james-clear/",
    cover: "https://is1-ssl.mzstatic.com/image/thumb/Publication124/v4/9f/fa/b1/9ffab177-c377-2e1d-84ad-e80629ec2e9e/9781473565425.jpg/1200x1200bb.jpg",
    categories: ["Business", "Self Help", "Bestsellers"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "260 MB",
    infoHash: "b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1",
    source: "torrent"
  },
  {
    id: "sapiens1",
    rawTitle: "Sapiens: A Brief History of Humankind - Yuval Noah Harari",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    narrator: "Derek Perkins",
    duration: "15 hrs and 17 mins",
    description: "One hundred thousand years ago, at least six different species of humans inhabited Earth. Yet today there is only one: Homo sapiens.",
    url: "https://audiobookbay.lu/abss/sapiens-yuval-noah-harari/",
    cover: "https://covers.openlibrary.org/b/id/8315112-L.jpg",
    categories: ["Business", "Self Help", "Bestsellers"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "510 MB",
    infoHash: "f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6",
    source: "torrent"
  },
  {
    id: "deepwork1",
    rawTitle: "Deep Work - Cal Newport",
    title: "Deep Work",
    author: "Cal Newport",
    narrator: "Jeff Bottoms",
    duration: "7 hrs and 44 mins",
    description: "Rules for Focused Success in a Distracted World: Master the superpower of our competitive economy.",
    url: "https://audiobookbay.lu/abss/deep-work-cal-newport/",
    cover: "https://covers.openlibrary.org/b/id/8233156-L.jpg",
    categories: ["Business", "Self Help"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "320 MB",
    infoHash: "a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7",
    source: "torrent"
  },
  {
    id: "canthurtme1",
    rawTitle: "Can't Hurt Me - David Goggins",
    title: "Can't Hurt Me",
    author: "David Goggins",
    narrator: "David Goggins, Adam Skolnick",
    duration: "13 hrs and 37 mins",
    description: "Master Your Mind and Defy the Odds: For David Goggins, childhood was a nightmare. Through self-discipline, mental toughness, and hard work, he transformed himself.",
    url: "https://audiobookbay.lu/abss/cant-hurt-me-david-goggins/",
    cover: "https://covers.openlibrary.org/b/id/8724103-L.jpg",
    categories: ["Self Help", "Bestsellers"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "610 MB",
    infoHash: "b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8",
    source: "torrent"
  },

  // Classics
  {
    id: "1984george",
    rawTitle: "1984 - George Orwell",
    title: "1984",
    author: "George Orwell",
    narrator: "Simon Prebble",
    duration: "11 hrs and 22 mins",
    description: "Winston Smith toes the Party line, rewriting history to satisfy the Ministry of Truth. But deep down, he harbors rebellion against Big Brother.",
    url: "https://audiobookbay.lu/abss/1984-george-orwell/",
    cover: "https://covers.openlibrary.org/b/id/8575708-L.jpg",
    categories: ["Classic", "Dystopian", "Sci-Fi"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "320 MB",
    infoHash: "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0",
    source: "torrent"
  },
  {
    id: "bravenewworld1",
    rawTitle: "Brave New World - Aldous Huxley",
    title: "Brave New World",
    author: "Aldous Huxley",
    narrator: "Michael York",
    duration: "8 hrs and 3 mins",
    description: "A chilling vision of a consumerist future where humans are genetically bred, socially conditioned, and pharmaceutically anesthetized.",
    url: "https://audiobookbay.lu/abss/brave-new-world-aldous-huxley/",
    cover: "https://covers.openlibrary.org/b/id/8226194-L.jpg",
    categories: ["Classic", "Dystopian", "Sci-Fi"],
    format: "M4B",
    bitrate: "128 Kbps",
    size: "310 MB",
    infoHash: "d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0",
    source: "torrent"
  },
  {
    id: "greatgatsby1",
    rawTitle: "The Great Gatsby - F. Scott Fitzgerald",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    narrator: "Jake Gyllenhaal",
    duration: "4 hrs and 49 mins",
    description: "The exemplary novel of the Jazz Age, telling the tragic story of Jay Gatsby and his obsessive pursuit of Daisy Buchanan.",
    url: "https://audiobookbay.lu/abss/the-great-gatsby-f-scott-fitzgerald/",
    cover: "https://covers.openlibrary.org/b/id/8231991-L.jpg",
    categories: ["Classic", "Romance"],
    format: "MP3",
    bitrate: "128 Kbps",
    size: "180 MB",
    infoHash: "e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1",
    source: "torrent"
  }
];
